#
# GitLab CI
#

stages:
  - test
  - deploy

nosetests:
  stage: test
  image: python:3.7
  script:
    - pip3.7 install coverage nose
    - pip3.7 install -r requirements.txt
    - nosetests -vx --with-doctest tests

deploy_qa:
  stage: deploy
  image: ubuntu:18.04
  script:
    - BASE_URL=`echo $CI_REPOSITORY_URL | sed "s;\/*$CI_PROJECT_PATH.*;;"`
    - which git || ( apt-get update -y && apt-get -qq install git )
    - git clone "$BASE_URL/dsilabs/deploy-lib.git" /tmp/deploy
    - source /tmp/deploy/run.sh

deploy_prod:
  stage: deploy
  image: ubuntu:18.04
  script:
    - BASE_URL=`echo $CI_REPOSITORY_URL | sed "s;\/*$CI_PROJECT_PATH.*;;"`
    - which git || ( apt-get update -y && apt-get -qq install git )
    - git clone "$BASE_URL/gitdata/deploy-lib-prod.git" /tmp/deploy
    - source /tmp/deploy/deploy.sh
