#
# GitLab CI
#

image: python:3.7

before_script:
  - python3.7 --version

stages:
  test


nosetests:
  stage: test

  script:
    - pip3.7 install coverage nose
    - pip3.7 install -r requirements.txt
    - nosetests -vx --with-doctest tests


